<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,1,1,'5YWz5LqO5oiR5Lus');
$cfg_Cs[2]=array(0,1,1,'5pyN5Yqh6aG555uu');
$cfg_Cs[3]=array(2,1,1,'5ZG85Y+r5Lit5b+D');
$cfg_Cs[4]=array(2,1,1,'57u05L+d5pyN5Yqh');
$cfg_Cs[5]=array(0,2,1,'5oiQ5Yqf5qGI5L6L');
$cfg_Cs[6]=array(0,1,1,'5oiR5Lus55qE5a6i5oi3');
$cfg_Cs[7]=array(0,1,1,'5paw6Ze75Lit5b+D');
$cfg_Cs[8]=array(7,1,1,'6KGM5Lia5paw6Ze7');
$cfg_Cs[9]=array(7,1,1,'5YWs5Y+45paw6Ze7');
$cfg_Cs[10]=array(0,1,1,'6IGU57O75oiR5Lus');
$cfg_Cs[11]=array(10,1,1,'5Yqg5YWl5oiR5Lus');
$cfg_Cs[12]=array(10,1,1,'6IGU57O75pa55byP');
$cfg_Cs[13]=array(10,1,1,'5Zyo57q/55WZ6KiA');
?>