{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='2'/}
{dede:img ddimg='/uploads/allimg/150904/1-150Z4164A5.jpg' text='' width='1000' height='700'} /uploads/allimg/150904/1-150Z4164A5.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/150904/1-150Z4164F0.jpg' text='' width='1000' height='700'} /uploads/allimg/150904/1-150Z4164F0.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/150904/1-150Z4164G0.jpg' text='' width='1000' height='700'} /uploads/allimg/150904/1-150Z4164G0.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/150904/1-150Z4164G2.jpg' text='' width='1000' height='700'} /uploads/allimg/150904/1-150Z4164G2.jpg {/dede:img}
