{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='2'/}
{dede:img ddimg='/uploads/allimg/150904/1-150Z41A336.jpg' text='' width='1000' height='700'} /uploads/allimg/150904/1-150Z41A336.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/150904/1-150Z41A343.jpg' text='' width='1000' height='700'} /uploads/allimg/150904/1-150Z41A343.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/150904/1-150Z41A346.jpg' text='' width='1000' height='700'} /uploads/allimg/150904/1-150Z41A346.jpg {/dede:img}
