<div class="fl xwPic"> <a title="" href="[field:arcurl/]"> <img src="[field:picname/]"/> </a> </div>
        <div class="fr xwFont">
          <p class="data">2015-05-15</p>
          <a title="" href="[field:arcurl/]">
          <h3>[field:title/]</h3>
          <div class="pf">
            <p class="">[field:infos/]…</p>
          </div>
          </a>
          <div class="pa"> <a title="[field:title/]" href="[field:arcurl/]">了解更多</a> </div>
        </div>