<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1024,1059);
$z[2][4]['filename']="head.htm";
$z[3]=Array("field","",1256,1275);
$z[3][4]['name']="title";
$z[4]=Array("field","",1308,1360);
$z[4][4]['name']="pubdate";
$z[4][4]['function']="MyDate('Y-m-d',@me)";
$z[5]=Array("field","",1396,1414);
$z[5][4]['name']="body";
$z[6]=Array("include","",1556,1593);
$z[6][4]['filename']="footer.htm";

?>