<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1024,1059);
$z[2][4]['filename']="head.htm";
$z[3]=Array("field","",1256,1275);
$z[3][4]['name']="title";
$z[4]=Array("productimagelist","\r\n	<p><img src=\"[field:imgsrc/]\" title=\"DSC_0078.JPG\" style=\"white-space: normal; float: none;\"/></p>\r\n	",1326,1477);
$z[5]=Array("include","",1621,1658);
$z[5][4]['filename']="footer.htm";

?>