<a title="" href="[field:typelink /]" style="display:inline-block;">
          <p class="pm"> <img src="/public/images/else/fwpic2.jpg"/> </p>
          <h2> [field:typename /] </h2>
          <div class="wbCon">
            <p class="clearfix"> <span class="fl">设施维保： 电气、灯具、给排水、道具、装潢。<br />
              设备维保： 空调设备、制冷设备、厨房设备、速食设备、净水设备。<br />
              </span> </p>
          </div>
          </a>