<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1024,1059);
$z[2][4]['filename']="head.htm";
$z[3]=Array("type","<a title=\"\" href=\"[field:typelink /]\" style=\"display:inline-block;\">\r\n          <p class=\"pm\"> <img src=\"/public/images/else/fwpic1.jpg\"/> </p>\r\n          <h2> [field:typename /] </h2>\r\n          <div class=\"hjCon\">\r\n            <p class=\"\">店铺报修、派案管理、销案管理、<br />\r\n              账务管理、统计分析、店铺档案建立。</p>\r\n          </div>\r\n          </a>",1242,1673);
$z[3][4]['typeid']="3";
$z[4]=Array("type","<a title=\"\" href=\"[field:typelink /]\" style=\"display:inline-block;\">\r\n          <p class=\"pm\"> <img src=\"/public/images/else/fwpic2.jpg\"/> </p>\r\n          <h2> [field:typename /] </h2>\r\n          <div class=\"wbCon\">\r\n            <p class=\"clearfix\"> <span class=\"fl\">设施维保： 电气、灯具、给排水、道具、装潢。<br />\r\n              设备维保： 空调设备、制冷设备、厨房设备、速食设备、净水设备。<br />\r\n              </span> </p>\r\n          </div>\r\n          </a>",1745,2291);
$z[4][4]['typeid']="4";
$z[5]=Array("include","",2342,2379);
$z[5][4]['filename']="footer.htm";

?>