<?php
$z[0]=Array("field","(@me==\"\")? @me=\"   class='current'  \":@me=\"\";",324,419);
$z[0][4]['name']="typeid";
$z[0][4]['runphp']="yes";
$z[1]=Array("channel","\r\n		<li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n		",457,639);
$z[1][4]['type']="top";
$z[1][4]['currentstyle']="<li><a class='current' href='~typelink~'>~typename~</a></li>";
$z[2]=Array("channel","    \r\n	<li><a title=\"\" href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n	",907,1024);
$z[2][4]['type']="top";

?>