<?php
$z[0]=Array("global","",254,280);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("include","",997,1032);
$z[1][4]['filename']="head.htm";
$z[2]=Array("type","<a title=\"\" href=\"[field:typelink /]\"><img src=\"public/images/fw1.png\"/></a>",3895,4005);
$z[2][4]['typeid']="3";
$z[3]=Array("type","<a title=\"\" href=\"[field:typelink /]\"><img src=\"public/images/fw2.png\"/></a>",4041,4151);
$z[3][4]['typeid']="4";
$z[4]=Array("arclist","\r\n			<li> <a title=\"\" href=\"field:typeurl/]\"> <img src=\"[field:picname/]\"/>\r\n              <p class=\"pt\">[field:title /]</p>\r\n              </a> </li>\r\n			  ",4489,4708);
$z[4][4]['row']="4";
$z[4][4]['typeid']="5";
$z[4][4]['titlelen']="15";
$z[5]=Array("include","",5331,5368);
$z[5][4]['filename']="footer.htm";

?>