<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1024,1059);
$z[2][4]['filename']="head.htm";
$z[3]=Array("channel","\r\n        	<a href=\"[field:typeurl/]\"><dd>[field:typename/]</dd></a>\r\n			",1454,1666);
$z[3][4]['row']="10";
$z[3][4]['type']="son";
$z[3][4]['col']="1";
$z[3][4]['currentstyle']="<a href='~typelink~' ~rel~><dd class='current'>~typename~</dd></a>";
$z[4]=Array("include","",2998,3035);
$z[4][4]['filename']="footer.htm";

?>