<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1024,1059);
$z[2][4]['filename']="head.htm";
$z[3]=Array("channel","\r\n        	<a href=\"[field:typeurl/]\"><dd>[field:typename/]</dd></a>\r\n			",1398,1610);
$z[3][4]['row']="10";
$z[3][4]['type']="son";
$z[3][4]['col']="1";
$z[3][4]['currentstyle']="<a href='~typelink~' ~rel~><dd class='current'>~typename~</dd></a>";
$z[4]=Array("list","\r\n	<li>\r\n      <div class=\"clearfix xwCon\">\r\n        \r\n		<div class=\"fl xwPic\"> <a title=\"\" href=\"[field:arcurl/]\"> <img src=\"[field:picname/]\"/ width=\"210\" height=\"180\"> </a> </div>\r\n        <div class=\"fr xwFont\">\r\n          <p class=\"data\">[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</p>\r\n          <a title=\"\" href=\"[field:arcurl/]\">\r\n          <h3>[field:title/]</h3>\r\n          <div class=\"pf\">\r\n            <p class=\"\">[field:infos/]…</p>\r\n          </div>\r\n          </a>\r\n          <div class=\"pa\"> <a title=\"[field:title/]\" href=\"[field:arcurl/]\">了解更多</a> </div>\r\n        </div>\r\n		\r\n      </div>\r\n    </li>\r\n	",1684,2368);
$z[4][4]['pagesize']="8";
$z[4][4]['infolen']="150";
$z[5]=Array("pagelist","",2399,2458);
$z[5][4]['istitem']="index,pre,next,end,";
$z[5][4]['listsize']="5";
$z[6]=Array("include","",2474,2511);
$z[6][4]['filename']="footer.htm";

?>