<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1024,1059);
$z[2][4]['filename']="head.htm";
$z[3]=Array("list","\r\n			  <li>\r\n                <p class=\"pm\"> <img src=\"[field:picname/]\"> </p>\r\n                <p class=\"pf\">[field:title/]</p>\r\n              </li>\r\n			  ",1542,1734);
$z[3][4]['pagesize']="10";
$z[4]=Array("pagelist","",1845,1904);
$z[4][4]['istitem']="index,pre,next,end,";
$z[4][4]['listsize']="5";
$z[5]=Array("include","",1920,1957);
$z[5][4]['filename']="footer.htm";

?>